//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlycReSoft.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlycReSoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string bupidEnabled {
            get {
                return ResourceManager.GetString("bupidEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://bumc-florida.bumc.bu.edu/BUPID_TD/.
        /// </summary>
        public static string bupidUrl {
            get {
                return ResourceManager.GetString("bupidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter,Molecule,C,H,N,O,S,P,Lower Bound,Upper Bound
        ///A,G:Pentose,5,8,0,4,0,0,0,0
        ///B,G:dHex,6,10,0,4,0,0,0,0
        ///C,G:ΔHexA,6,6,0,5,0,0,0,0
        ///D,G:HexN,6,11,1,4,0,0,0,0
        ///E,G:Hexose,6,10,0,5,0,0,0,0
        ///F,G:HexA,6,8,0,6,0,0,0,0
        ///G,G:HexNAc,8,13,1,5,0,0,0,0
        ///H,G:NeuAc,11,17,1,8,0,0,0,0
        ///I,G:NeuGc,11,17,1,9,0,0,0,0
        ///J,G:Qui4FM,7,11,1,4,0,0,0,0
        ///K,G:GalNAcAn,8,12,2,5,0,0,0,0
        ///L,G:QuiNAC,8,13,1,4,0,0,0,0
        ///M,G:Kdo,8,12,0,7,0,0,0,0
        ///N,Ac,2,2,0,1,0,0,0,0
        ///O,Phosphate,0,1,0,3,0,1,0,0
        ///P,SO3,0,0,0,3,1,0,0,0
        ///Q,Water,0,2,0,1,0, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultComposition {
            get {
                return ResourceManager.GetString("DefaultComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -3.69288417,0.65784006,1.345376317,0.219899787,0.0000383503,-0.000349839,-0.001610525,-0.000947516,0.011453828
        ///.
        /// </summary>
        public static string DefaultFeatures {
            get {
                return ResourceManager.GetString("DefaultFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0,0,10.0,500,6000,80,5.0,1
        ///.
        /// </summary>
        public static string DefaultParameters {
            get {
                return ResourceManager.GetString("DefaultParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecular Weight,C,Compositions,GalNAcS,GalP,GalS,NeuGc,Hex,Pen,Fuc,Neu,HexNAc,NeuAcAc,ManP,Kdn,HexN,HexA,GlcNAcS,Xxx,GlcAS,GalNAcS2,Rha,Xyl,NeuAc,Water,Adduct/Replacement,Adduct Amount,Peptide Sequence,Peptide Modification,Peptide Missed Cleavage Number,Number of Glycan Attachment to Peptide,Start AA,End AA
        ///2882.0466697887005,0,[0;0;0;0;8;0;1;0;7;0;0;0;0;0;0;0;0;0;0;0;0],0,0,0,0,8,0,1,0,7,0,0,0,0,0,0,0,0,0,0,0,0,1,/0,0,,,0,0,0,0
        ///1543.5090740986998,0,[1;0;0;0;3;0;1;0;3;0;0;0;0;0;0;0;0;0;0;0;0],1,0,0,0,3,0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Human_GlycomeDB_All {
            get {
                return ResourceManager.GetString("Human_GlycomeDB_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecular Weight,C,Compositions,GalNAcS,GalS,NeuGc,Hex,Kdn,NeuAc,Fuc,Xyl,HexNAc,Water,Adduct/Replacement,Adduct Amount,Peptide Sequence,Peptide Modification,Peptide Missed Cleavage Number,Number of Glycan Attachment to Peptide,Start AA,End AA
        ///2882.0466697887005,0,[0;0;0;8;0;0;1;0;7],0,0,0,8,0,0,1,0,7,1,/0,0,,,0,0,0,0
        ///3025.0685274837006,0,[0;0;0;6;0;3;1;0;5],0,0,0,6,0,3,1,0,5,1,/0,0,,,0,0,0,0
        ///1543.5090740986998,0,[1;0;0;3;0;0;1;0;3],1,0,0,3,0,0,1,0,3,1,/0,0,,,0,0,0,0
        ///3025.0685274837006,0,[0;0;0;6;0;3;1;0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Human_GlycomeDB_NLinked {
            get {
                return ResourceManager.GetString("Human_GlycomeDB_NLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecular Weight,C,Compositions,GalNAcS,GalP,GalS,NeuGc,Hex,Pen,Fuc,Neu,HexNAc,NeuAcAc,ManP,Kdn,HexN,HexA,GlcNAcS,Xxx,GlcAS,GalNAcS2,Rha,Xyl,NeuAc,Water,Adduct/Replacement,Adduct Amount,Peptide Sequence,Peptide Modification,Peptide Missed Cleavage Number,Number of Glycan Attachment to Peptide,Start AA,End AA
        ///1167.3245080787,0,[0;0;0;0;3;0;0;0;2;0;0;0;0;0;0;0;1;0;0;0;0],0,0,0,0,3,0,0,0,2,0,0,0,0,0,0,0,1,0,0,0,0,1,/0,0,,,0,0,0,0
        ///896.3485158336999,0,[0;0;0;0;2;0;1;0;1;0;0;0;0;0;0;1;0;0;0;0;0],0,0,0,0,2,0,1,0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Human_GlycomeDB_OLinked {
            get {
                return ResourceManager.GetString("Human_GlycomeDB_OLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecular Weight,C,Compositions,GalNAcS,GalP,GalS,NeuGc,Hex,GlcS,Pen,Fuc,Neu,GlcAS,NeuAcAc,ManP,Kdn,HexN,HexA,GlcNAcP,GlcNAcS,Xxx,HexNAc,GalNAcS2,Rha,Xyl,NeuAc,Water,Adduct/Replacement,Adduct Amount,Peptide Sequence,Peptide Modification,Peptide Missed Cleavage Number,Number of Glycan Attachment to Peptide,Start AA,End AA
        ///2882.0466697887005,0,[0;0;0;0;8;0;0;1;0;0;0;0;0;0;0;0;0;0;7;0;0;0;0],0,0,0,0,8,0,0,1,0,0,0,0,0,0,0,0,0,0,7,0,0,0,0,1,/0,0,,,0,0,0,0
        ///1543.5090740986998,0,[1;0;0;0;3;0;0;1;0;0;0;0;0;0;0;0;0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Mammalian_GlycomeDB_All {
            get {
                return ResourceManager.GetString("Mammalian_GlycomeDB_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecular Weight,C,Compositions,GalNAcS,GalS,GlcNAcP,GlcNAcS,NeuGc,Hex,Kdn,NeuAc,Fuc,Xyl,HexNAc,NeuAcAc,Water,Adduct/Replacement,Adduct Amount,Peptide Sequence,Peptide Modification,Peptide Missed Cleavage Number,Number of Glycan Attachment to Peptide,Start AA,End AA
        ///2882.0466697887005,0,[0;0;0;0;0;8;0;0;1;0;7;0],0,0,0,0,0,8,0,0,1,0,7,0,1,/0,0,,,0,0,0,0
        ///1543.5090740986998,0,[1;0;0;0;0;3;0;0;1;0;3;0],1,0,0,0,0,3,0,0,1,0,3,0,1,/0,0,,,0,0,0,0
        ///1640.5921726036997,0,[0;0;0;0;0;5;0;0;0;0;4;0],0,0,0,0,0,5,0,0,0,0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Mammalian_GlycomeDB_NLinked {
            get {
                return ResourceManager.GetString("Mammalian_GlycomeDB_NLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecular Weight,C,Compositions,GalNAcS,GalP,GalS,NeuGc,Hex,GlcS,Pen,Fuc,Neu,GlcAS,NeuAcAc,ManP,Kdn,HexN,HexA,GlcNAcP,GlcNAcS,Xxx,HexNAc,GalNAcS2,Rha,Xyl,NeuAc,Water,Adduct/Replacement,Adduct Amount,Peptide Sequence,Peptide Modification,Peptide Missed Cleavage Number,Number of Glycan Attachment to Peptide,Start AA,End AA
        ///1167.3245080787,0,[0;0;0;0;3;0;0;0;0;1;0;0;0;0;0;0;0;0;2;0;0;0;0],0,0,0,0,3,0,0,0,0,1,0,0,0,0,0,0,0,0,2,0,0,0,0,1,/0,0,,,0,0,0,0
        ///2153.7979276487,0,[0;0;0;0;6;0;0;1;0;0;0;0;0;0;0;0;0;1;4;0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Mammalian_GlycomeDB_OLinked {
            get {
                return ResourceManager.GetString("Mammalian_GlycomeDB_OLinked", resourceCulture);
            }
        }
    }
}
